version: '3'

services:
  myapp:
    image: trainingtest:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/logs
    environment:
      NODE_ENV: production
    networks:
      - mds0

networks:
  mds0:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.0.0/24"