version: '3'

services:
  wordpress:
    container_name: DockerCompose
    image: wordpress:latest
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - /app/logs
    networks:
      - docker_compose_wordpress
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.6.4-focal
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: wordpress
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - docker_compose_wordpress


networks:
  docker_compose_wordpress:
    driver: bridge
    ipam:
      config:
        - subnet: "172.18.0.0/24"

volumes:
  mariadb_data:
