version: '3'

services:
  backend:
    container_name: DockerBack
    image: keyroz/backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    environment:
      MONGO_URI: mongodb://mongodb:27017
    ports:
      - 8081:8081
    depends_on:
      - mongodb
    networks:
      - mongodb_network
  
  frontend:
    container_name: DockerFront
    image: keyroz/frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      VITE_GRAPHQL_URL: http://backend:8081/graphql
    links:
      - backend
    ports:
      - 4000:80
    depends_on:
      - backend
    networks:
      - mongodb_network
  
  mongodb:
    container_name: MongoDB
    image: mongo:latest
    volumes:
      - mongodb_data:/var/lib/mongo
    ports:
      - 27017:27017
    networks:
      - mongodb_network

volumes:
  mongodb_data:

networks:
  mongodb_network:
    name: mongodb_network
    driver: bridge
